#!/usr/bin/env python

from time import sleep

COMPILE_COFFEE = True


def shell(cmd, ps):
    from subprocess import Popen
    print '+ $', cmd,
    p = Popen(cmd, shell=True)
    print '[PID %d]' % p.pid
    ps.append(p)


def main():
    try:
        ps = []
        shell('sass --watch ./app/src/sass/style.sass:./app/assets/styles/style.css', ps)
        shell('jade --watch -o ./app/views ./app/src/jade', ps)
        if COMPILE_COFFEE:
            shell('coffee --watch --output ./app/assets/scripts --compile ./app/src/coffee', ps)
        while True:
            raw_input()
    except KeyboardInterrupt:
        pass
    finally:
        print
        print 'Sending all processes the TERM signal...'
        for p in ps: p.terminate()
        sleep(0.3)
        print 'Sending all processes the KILL signal...'
        for p in ps: p.kill()
        print 'Live compile stopped.'

if __name__ == '__main__':
    main()
