// Generated by CoffeeScript 1.7.1
(function() {
  require(["$api/models", "scripts/example-language", "scripts/example-cover", "scripts/example-button", "scripts/example-playlist"], function(models, languageExample, coverExample, buttonExample, playlistExample) {
    "use strict";
    languageExample.doHelloWorld();
    coverExample.doCoverForAlbum();
    buttonExample.doShareButtonForArtist();
    buttonExample.doPlayButtonForAlbum();
    playlistExample.doPlaylistForAlbum();
  });

}).call(this);
