// Generated by CoffeeScript 1.7.1
(function() {
  require(["$api/models", "$views/image#Image"], function(models, Image) {
    "use strict";
    var doCoverForAlbum;
    doCoverForAlbum = function() {
      var album, image;
      album = models.Album.fromURI("spotify:album:2mCuMNdJkoyiXFhsQCLLqw");
      image = Image.forAlbum(album, {
        width: 200,
        height: 200,
        player: true
      });
      document.getElementById("albumCoverContainer").appendChild(image.node);
    };
    exports.doCoverForAlbum = doCoverForAlbum;
  });

}).call(this);
